DROP TABLE PROJECT_INFO;
CREATE TABLE PROJECT_INFO (
  ID                 VARCHAR(50) NOT NULL PRIMARY KEY,
  NAME               VARCHAR(50),
  PROJECT_MANAGER    VARCHAR(50),
  SOLUTION_ARCHITECT VARCHAR(50),
  CREATED_DATE        DATE,
  UPDATED_DATE       DATE,
  CONSTRAINT PROJ_NAME_UNQ UNIQUE (name)
);